# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ariji\Desktop\A.X.E.L - 2.0\AXEL_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_border = QtWidgets.QLabel(self.centralwidget)
        self.bg_border.setGeometry(QtCore.QRect(0, 0, 731, 401))
        self.bg_border.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border  : 1px Solid blue;")
        self.bg_border.setText("")
        self.bg_border.setScaledContents(True)
        self.bg_border.setObjectName("bg_border")
        self.start_botton = QtWidgets.QPushButton(self.centralwidget)
        self.start_botton.setGeometry(QtCore.QRect(590, 20, 101, 41))
        self.start_botton.setStyleSheet("background-color:transparent;\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color : white;\n"
"")
        self.start_botton.setObjectName("start_botton")
        self.exit_botton = QtWidgets.QPushButton(self.centralwidget)
        self.exit_botton.setGeometry(QtCore.QRect(580, 70, 121, 41))
        self.exit_botton.setStyleSheet("background-color:transparent;\n"
"font: 63 12pt \"Segoe UI Semibold\";\n"
"color : white;\n"
"")
        self.exit_botton.setObjectName("exit_botton")
        self.gif1 = QtWidgets.QLabel(self.centralwidget)
        self.gif1.setGeometry(QtCore.QRect(10, 10, 191, 141))
        self.gif1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 1px solid blue\n"
"")
        self.gif1.setText("")
        self.gif1.setPixmap(QtGui.QPixmap("Database/GUI/earth.gif"))
        self.gif1.setScaledContents(True)
        self.gif1.setObjectName("gif1")
        self.reactor = QtWidgets.QLabel(self.centralwidget)
        self.reactor.setGeometry(QtCore.QRect(230, 70, 271, 271))
        self.reactor.setAutoFillBackground(False)
        self.reactor.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.reactor.setText("")
        self.reactor.setPixmap(QtGui.QPixmap("C:\\Users\\ariji\\Desktop\\A.X.E.L - 2.0\\Database/GUI/reactor.gif"))
        self.reactor.setScaledContents(True)
        self.reactor.setObjectName("reactor")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 170, 191, 31))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 170, 255);\n"
"border: 0.5px solid blue;")
        self.textBrowser.setObjectName("textBrowser")
        self.reactor_2 = QtWidgets.QLabel(self.centralwidget)
        self.reactor_2.setGeometry(QtCore.QRect(20, 210, 181, 181))
        self.reactor_2.setAutoFillBackground(False)
        self.reactor_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.reactor_2.setText("")
        self.reactor_2.setPixmap(QtGui.QPixmap("C:\\Users\\ariji\\Desktop\\A.X.E.L - 2.0\\Database/GUI/scifi.gif"))
        self.reactor_2.setScaledContents(True)
        self.reactor_2.setObjectName("reactor_2")
        self.reactor_3 = QtWidgets.QLabel(self.centralwidget)
        self.reactor_3.setGeometry(QtCore.QRect(530, 220, 191, 171))
        self.reactor_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 1px solid blue;")
        self.reactor_3.setText("")
        self.reactor_3.setPixmap(QtGui.QPixmap("C:\\Users\\ariji\\Desktop\\A.X.E.L - 2.0\\Database/GUI/reactor2.gif"))
        self.reactor_3.setScaledContents(True)
        self.reactor_3.setObjectName("reactor_3")
        self.axel = QtWidgets.QLabel(self.centralwidget)
        self.axel.setGeometry(QtCore.QRect(280, 310, 171, 41))
        self.axel.setText("")
        self.axel.setPixmap(QtGui.QPixmap("C:\\Users\\ariji\\Desktop\\A.X.E.L - 2.0\\Database/GUI/axel.png"))
        self.axel.setScaledContents(True)
        self.axel.setObjectName("axel")
        self.scifi_terminal = QtWidgets.QLabel(self.centralwidget)
        self.scifi_terminal.setGeometry(QtCore.QRect(540, 120, 171, 91))
        self.scifi_terminal.setText("")
        self.scifi_terminal.setPixmap(QtGui.QPixmap("C:\\Users\\ariji\\Desktop\\A.X.E.L - 2.0\\Database/GUI/Code.gif"))
        self.scifi_terminal.setObjectName("scifi_terminal")
        self.exit_bg = QtWidgets.QLabel(self.centralwidget)
        self.exit_bg.setGeometry(QtCore.QRect(580, 70, 121, 41))
        self.exit_bg.setText("")
        self.exit_bg.setPixmap(QtGui.QPixmap("C:\\Users\\ariji\\Desktop\\A.X.E.L - 2.0\\Database/GUI/botton.jpg"))
        self.exit_bg.setScaledContents(True)
        self.exit_bg.setObjectName("exit_bg")
        self.start_bg = QtWidgets.QLabel(self.centralwidget)
        self.start_bg.setGeometry(QtCore.QRect(580, 20, 121, 41))
        self.start_bg.setText("")
        self.start_bg.setPixmap(QtGui.QPixmap("C:\\Users\\ariji\\Desktop\\A.X.E.L - 2.0\\Database/GUI/botton.jpg"))
        self.start_bg.setScaledContents(True)
        self.start_bg.setObjectName("start_bg")
        self.initiating = QtWidgets.QLabel(self.centralwidget)
        self.initiating.setGeometry(QtCore.QRect(180, 20, 411, 91))
        self.initiating.setText("")
        self.initiating.setPixmap(QtGui.QPixmap("C:\\Users\\ariji\\Desktop\\A.X.E.L - 2.0\\Database/GUI/initial.gif"))
        self.initiating.setScaledContents(False)
        self.initiating.setObjectName("initiating")
        self.bg_border.raise_()
        self.reactor.raise_()
        self.textBrowser.raise_()
        self.reactor_2.raise_()
        self.reactor_3.raise_()
        self.axel.raise_()
        self.scifi_terminal.raise_()
        self.initiating.raise_()
        self.exit_bg.raise_()
        self.exit_botton.raise_()
        self.start_bg.raise_()
        self.start_botton.raise_()
        self.gif1.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_botton.setText(_translate("MainWindow", "START"))
        self.exit_botton.setText(_translate("MainWindow", "EXIT"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
